apiVersion:  autoscaling/v1
kind:  HorizontalPodAutoscaler
metadata:
  name:  web-autoscaler
  namespace:  dev
spec:
  maxReplicas:  10
  minReplicas:  2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: web-deployment
  targetCPUUtilizationPercentage: 50
