apiVersion:  apps/v1
kind:  Deployment
metadata:
  name: web-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      name: webapp
  template:
    metadata:
      labels:
        name: webapp
    spec:
      containers:
      - image: dragrom/kubeserve:v1
        name: web
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "20m"

