apiVersion: v1
kind: Service
metadata:
  namespace: wordpress
  name: mysql   # will be used as a value in
  labels:                 # WORDPRESS_DB_HOST in wordpress-deploy.yml
    app: wordpress
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: wordpress
    tier: mysql
---
apiVersion:  apps/v1
kind: Deployment
metadata:
  namespace: wordpress
  name: mysql
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: mysql-persistent-volume
      containers:
      - image: mysql:5.7
        name: mysql
        args:
          - "--innodb_use_native_aio=0"
          - "--bind-address=0.0.0.0"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass        # the one generated before in secret.yml
              key: password
        - name: MYSQL_ROOT_HOST
          value: '%'
        
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: storage  # which data will be stored
          mountPath: /var/lib/mysql
          subPath: mysql