kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: wordpress
  name: mysql-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: wordpress
  name: wordpress-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer