apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wordpress
  name: wordpress-persistent-volume
  labels:
    app: wordpress
    tier: frontend
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wordpress
  name: mysql-persistent-volume
  labels:
    app: wordpress
    tier: mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi