apiVersion:  autoscaling/v2beta1
kind:  HorizontalPodAutoscaler
metadata:
  name:  web-autoscaler
  namespace:  dev
spec:
  maxReplicas:  10
  minReplicas:  5
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: web-deployment
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50

