apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace:  dev
  labels:
    name: "web_application"
spec:
  containers:
  - name: webapp
    image: dragrom/exemple_deployment:v1
    ports:
    - containerPort: 80
