apiVersion: v1
kind: Pod
metadata:
  name: webpod
  namespace:  dev
  labels:
    name: "web_application"
spec:
  containers:
  - name: webapp
    image: dragrom/exemple_deployment:v1
    volumeMounts:
    - mountPath:  /usr/share/nginx/html
      name:  www
  volumes:
  - name:  www
    hostPath: 
      path: /vagrant
      type: Directory
