apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  namespace:  dev
  labels:
    name: "web_application"
spec:
  containers:
  - name: web
    image: dragrom/exemple_deployment:v1
    volumeMounts:
    - mountPath:  /usr/share/nginx/html
      name:  www
  - name: database
    image: mysql:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password        
    ports:
    - containerPort: 3306
  volumes:
  - name:  www
    hostPath: 
      path: /vagrant
      type: Directory
